title: "sabbour."
description: Product Manager on the Azure Kubernetes Service (AKS) team with a background in product marketing, technical sales, cloud architecture, developer evangelism, and software engineering. The views and opinions expressed here are mine, and not those of my employer.
author: Ahmed Sabbour
url: https://sabbour.me
baseurl: ""
twitter:
  username: sabbour
social:
  name: Ahmed Sabbour
  links:
    - https://twitter.com/sabbour
    - https://www.linkedin.com/in/ahmedsabbour
    - https://github.com/sabbour
image: /assets/images/og-default.png
plugins:
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - scripts
  - pages/tags.md