title: Ahmed Sabbour
description: Product Manager on the Azure Kubernetes Service (AKS) team with a background in product marketing, technical sales, cloud architecture, developer evangelism, and software engineering. The views and opinions expressed here are mine, and not those of my employer.
author:
  name: Ahmed Sabbour
url: https://sabbour.me
social:
  twitter: sabbour
  github: sabbour
  linkedin: ahmedsabbour
  stackoverflow: 47582/sabbour
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap